version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: match-report-frontend-app
    command: .docker/start.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
      - 5555:5555
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db:
    build: ./.docker/mongo
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: db
    volumes:
      - mongodb_data:/data/db

  db_test:
    build: ./.docker/mongo
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: db_test
    volumes:
      - mongodb_data_test:/data/db

volumes:
  mongodb_data:
    driver: local
  mongodb_data_test:
    driver: local

networks:
  my-network:
    external: true
